---
title: "Screen Time Usage Project"
author: "Daniel Kouassi"
date: "2024-04-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(readxl)
library(tidyverse)

ScreenTime <- read_excel("C:/Users/Daniel Kouassi/Desktop/Spring 2024/DATA 211 -50 Data Science/Data/ScreenTime.xlsx")

# Convert Worked variable to factor
ScreenTime$Worked <- factor(ScreenTime$Worked, levels = c("No", "Yes"))

# Perform one-sample t-test
t.test(ScreenTime$Daily_Screen_TimeInHours_Usage ~ ScreenTime$Worked, alternative = "less")


boxplot <- ggplot(ScreenTime, aes(x = Worked, y = ScreenTime$Daily_Screen_TimeInHours_Usage, fill = Worked)) +
  geom_boxplot() +
  labs(title = "Boxplot of Daily Screen Time Usage",
       x = "Worked (Yes/No)",
       y = "Daily Screen Time Usage (hours)") +
  scale_fill_manual(values = c("blue", "green")) +
  theme_minimal()

# Print the boxplot
print(boxplot)

```

